apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: robo-shop-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: c1
            url: https://kubernetes.default.svc
          - cluster: c2
            url: https://BB10DFEF6A9911E9EF30063A3581176B.sk1.ap-south-1.eks.amazonaws.com
  template:
    metadata:
      name: robo-shop-{{cluster}}  
    spec:
      project: default
      source:
        repoURL: https://github.com/Swapnil-070904/robo-shop.git
        targetRevision: main
        path: EKS/helm  
        helm:
          releaseName: roboshop
      destination:
        server: "{{url}}"  
        namespace: robot-shop  
      syncPolicy:
        automated:
          prune: true  
          selfHeal: true  
        syncOptions:
          - CreateNamespace=true  
