# Registry and repository for Docker images
# Default is docker/robotshop/image:latest
image:
  repo: ak6805002
  pullPolicy: Always
# EUM configuration
# Provide your key and set the endpoint
# eum:
#   key: null
#   url: https://eum-eu-west-1.instana.io

redis:
  # Storage class to use with redis statefulset.
  storageClassName: gp2
